### ISSUE TITLE
Bug: Websocket connection occasionally closes

### ISSUE THREAD

**Issue by alastairong** [holochain/elemental-chat-ui#15]
Sometimes the websocket connection closes and then messages won't be received / new messages can't be sent. Browser does not appear to recover from this. We should at least implement a notification to reload the page if the websocket connection dies (auto-reconnecting would be great too)

![image](https://user-images.githubusercontent.com/16625137/97462515-b75a2a00-1936-11eb-8f34-67a206cf7944.png)

**Comment by philipbeadle** [comment]
Ive added in code that will reconnect the socket after 1 second when it closes.

holochainClient.onclose = function(e) {
            console.log('Socket is closed. Reconnect will be attempted in 1 second.', e.reason);
            setTimeout(function() {
              dispatch("initialiseAgent");
            }, 1000);
          };

**Comment by zippy** [comment]
obsolete
