### ISSUE TITLE
Bug: UI tries to load data before connected to HoloPort

### ISSUE THREAD

**Issue by alastairong** [holochain/elemental-chat-ui#16]
Page tries to call listchannel before establishing AppWebSocket connection. Users then have to manually click the "check for new channels" button to get the list and start to receive periodic updates.

![image](https://user-images.githubusercontent.com/16625137/97464396-c510af00-1938-11eb-9c63-f1284e05dcc3.png)

**Comment by philipbeadle** [comment]
I moved committing the socket to after the rest of the code that sets up the agent etc so when the fetch channels fires there will be an agent key etc ready to go.

**Comment by zippy** [comment]
can we close this?

**Comment by alastairong** [comment]
yea
