### ISSUE TITLE
Elemental chat UI won't work on Safari

### ISSUE THREAD

**Issue by peeech** [holochain/elemental-chat-ui#6]
Code is using method Blob.arrayBuffer() that is not supported on any Safari or older Chromes or Mozillas. Current market support for this method is [73%](https://caniuse.com/?search=blob%20array).

#### How to reproduce:
Open elemental chat on Safari, you will see in console an error:
```
Uncaught (in promise) TypeError: data.arrayBuffer is not a function
```

**Comment by philipbeadle** [comment]
Fixed it, found a patch for it.
https://gist.github.com/hanayashiki/8dac237671343e7f0b15de617b0051bd
